"""Report generation endpoint."""

from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.property import Property
from app.models.scenario import DevelopmentScenario

router = APIRouter()


REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Development Analysis Report - {address}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #333; }}
        h1 {{ color: #1a365d; border-bottom: 3px solid #2b6cb0; padding-bottom: 10px; }}
        h2 {{ color: #2b6cb0; margin-top: 30px; }}
        .header {{ display: flex; justify-content: space-between; align-items: center; }}
        .score {{ font-size: 48px; font-weight: bold; color: {score_color}; }}
        .score-label {{ font-size: 14px; color: #666; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px 15px; text-align: left; border-bottom: 1px solid #e2e8f0; }}
        th {{ background-color: #ebf8ff; color: #2b6cb0; }}
        .scenario {{ background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 15px 0; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #2b6cb0; }}
        .metric-label {{ font-size: 12px; color: #666; }}
        .risk {{ background: #fff5f5; border-left: 4px solid #fc8181; padding: 8px 12px; margin: 5px 0; }}
        .disclaimer {{ font-size: 11px; color: #999; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 10px; }}
        @media print {{ body {{ margin: 20px; }} }}
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>Development Analysis Report</h1>
            <p><strong>{address}</strong> | Parcel: {parcel_id} | Zoning: {zoning_code}</p>
        </div>
        <div style="text-align: center;">
            <div class="score">{opportunity_score}</div>
            <div class="score-label">Opportunity Score</div>
        </div>
    </div>

    <h2>Property Overview</h2>
    <table>
        <tr><th>Lot Size</th><td>{lot_area_sqft} sq ft</td></tr>
        <tr><th>Current Use</th><td>{current_use}</td></tr>
        <tr><th>Assessed Value</th><td>${assessed_value}</td></tr>
        <tr><th>Zoning</th><td>{zoning_code} - {zoning_description}</td></tr>
        <tr><th>Heritage</th><td>{is_heritage}</td></tr>
        <tr><th>Floodplain</th><td>{is_floodplain}</td></tr>
    </table>

    <h2>Development Scenarios</h2>
    {scenarios_html}

    <div class="disclaimer">
        <strong>Disclaimer:</strong> This AI-generated analysis is for informational purposes only.
        It does not constitute legal, financial, or professional advice.
        Consult qualified professionals before making investment decisions.
        <br>Generated by RealtorDevOpsAI | {generated_date}
    </div>
</body>
</html>
"""


def _format_currency(value: float | None) -> str:
    if value is None:
        return "N/A"
    return f"${value:,.0f}"


def _score_color(score: float) -> str:
    if score >= 70:
        return "#38a169"
    if score >= 40:
        return "#d69e2e"
    return "#e53e3e"


def _build_scenarios_html(scenarios: list[DevelopmentScenario]) -> str:
    html_parts = []
    for s in scenarios:
        risks_html = ""
        if s.risks and isinstance(s.risks, dict):
            for risk in s.risks.get("items", []):
                risks_html += f'<div class="risk">{risk}</div>'

        html_parts.append(f"""
        <div class="scenario">
            <h3>{s.title}</h3>
            <p>{s.description}</p>
            <div>
                <div class="metric">
                    <div class="metric-value">{_format_currency(s.total_cost)}</div>
                    <div class="metric-label">Total Cost</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{s.roi_pct:.1f}%</div>
                    <div class="metric-label">ROI</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{_format_currency(s.profit)}</div>
                    <div class="metric-label">Profit</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{s.timeline_months} mo</div>
                    <div class="metric-label">Timeline</div>
                </div>
                <div class="metric">
                    <div class="metric-value">{s.proposed_units or 'N/A'}</div>
                    <div class="metric-label">Units</div>
                </div>
            </div>
            {f'<h4>Risks</h4>{risks_html}' if risks_html else ''}
        </div>
        """)
    return "\n".join(html_parts)


@router.get("/property/{property_id}/pdf")
async def generate_pdf_report(
    property_id: UUID,
    db: AsyncSession = Depends(get_db),
):
    """Generate a PDF report for a property analysis."""
    # Fetch property
    result = await db.execute(select(Property).where(Property.id == property_id))
    prop = result.scalar_one_or_none()
    if not prop:
        raise HTTPException(status_code=404, detail="Property not found")

    # Fetch scenarios
    scenario_result = await db.execute(
        select(DevelopmentScenario)
        .where(DevelopmentScenario.property_id == property_id)
        .order_by(DevelopmentScenario.opportunity_score.desc())
    )
    scenarios = scenario_result.scalars().all()

    # Calculate overall score
    if scenarios:
        overall_score = sum(s.opportunity_score or 0 for s in scenarios) / len(scenarios)
    else:
        overall_score = 0

    # Build HTML
    html = REPORT_HTML_TEMPLATE.format(
        address=prop.address,
        parcel_id=prop.parcel_id,
        zoning_code=prop.zoning_code or "N/A",
        zoning_description=prop.zoning_description or "",
        lot_area_sqft=f"{prop.lot_area_sqft:,.0f}" if prop.lot_area_sqft else "N/A",
        current_use=prop.current_use or "N/A",
        assessed_value=f"{prop.assessed_value:,.0f}" if prop.assessed_value else "N/A",
        is_heritage="Yes" if prop.is_heritage else "No",
        is_floodplain="Yes" if prop.is_floodplain else "No",
        opportunity_score=f"{overall_score:.0f}",
        score_color=_score_color(overall_score),
        scenarios_html=_build_scenarios_html(scenarios),
        generated_date="Generated by RealtorDevOpsAI",
    )

    # Generate PDF using WeasyPrint
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
    except ImportError:
        # Fallback: return HTML if WeasyPrint not installed
        return StreamingResponse(
            iter([html.encode()]),
            media_type="text/html",
            headers={"Content-Disposition": f'attachment; filename="report-{prop.parcel_id}.html"'},
        )

    return StreamingResponse(
        iter([pdf_bytes]),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="report-{prop.parcel_id}.pdf"'},
    )
